# One entry per line. Empty lines and comment lines (#) are ignored.

# essentials
darkly
bitwarden

# version control
git
git-extras
#git-flow
subversion
diff-so-fancy
git-delta
tig

# Archive
7zip
p7zip
p7zip-plugins
p7zip-doc
p7zip-gui
#p7zip-full
#p7zip-rar
unrar
zip
unzip

# Fonts
fira-code-fonts
powerline-fonts
lyx-fonts

# file manager & synchronisation
grsync
unison
unison-gtk
mc
#searchmonkey (see searchmonkey.dev)
fsearch
rclone
rclone-browser

# Office
libreoffice-headless
libreoffice-pyuno
#openclipart
#openclipart-libreoffice
unoconv
odt2txt
tesseract
tesseract-langpack-*
ocrmypdf

# Groupware & Internet
wget
curl
yt-dlp
aria2

# Graphic & CAD
perl-Image-ExifTool
ImageMagick

# Tools
#yakuake
cutecom
minicom
moserial
putty
tio
gtkterm

# Ausweis App
pcscd
pcsc-lite-ccid
ausweisapp2

# Ausweis App
pcscd
libccid
ausweisapp2

# virtual environment
wine
#virtualbox

# Perl
perl
perl-doc

# CLI tools
micro
catdoc
#docx2txt
cmatrix
htop
inxi
fastfetch
sox
ocrmypdf
gettext
sox
#di
ncdu
gnupg2-scdaemon
xclip
bat
stress
clamav
glmark2
hardlink
rmlint
#rmlint-doc
prettyping
par2
nmap
tree
trash-cli
btop
tldr
highlight
atool
caca-utils
w3m
poppler-utils
oping
tmux
jq
progress
traceroute
stow
attr
#rtmpdump
#ffmpeg
ffmpegthumbs
golang-go
gnupg2
#fraqtive
pandoc
#ncal
util-linux
smartmontools
fd-find
ripgrep
xsltproc
libxml2
dos2unix

# Development
ncurses-compat-libs
yad
zenity
imake
makedepend
gcovr
arm-none-eabi-binutils-cs
arm-none-eabi-gdb
arm-none-eabi-gcc-cs
arm-none-eabi-newlib
doxygen
#doxygen-doc
doxygen-latex
doxygen-doxywizard
graphviz
graphviz-doc
ghostscript
asciidoctor
#asciidoctor-doc
gnuplot
labplot
#xmlcopyeditor
java-openjdk
readline-devel
pcre-devel
can-utils
assistant-qt6
designer-qt6
linguist-qt6
clang-format
stlink
stlink-gui
openocd
cppcheck
kicad
kicad-packages3d
kicad-doc

# Ruby
ruby-devel
rubygems
ri
#ruby-roo
bundler

# Python & Python packages
python3
python3-devel
python3-pip
pipx
python3-gpg
python3-brotli
python3-urllib3
gtk3-devel
gstreamer1-plugins-base
gstreamer1-plugins-base-devel
glib2-devel
xcb-util-cursor
freeglut
freeglut-devel
python3-gstreamer1
python3-wxpython4
#wxglade
python3-tkinter
python3-setuptools
python3-pyqt6-devel
#pyqt6-examples
python3-pyqt6
qt6-designer
#python3-pyqt6.qtmultimedia
#python3-pyqt6.qtserialport

# EOF
