# One entry per line. Empty lines and comment lines (#) are ignored.

development-tools
rpm-development-tools
c-development
authoring-and-publishing
container-management
virtualization-host
system-tools

# EOF
